version: '3.9'  

services: 

  api :
    build: .
    container_name: notes-api
    restart: always
    ports:
      - "4000:4000"
    environment:
      PORT : 4000
      MONGO_URI : "mongodb://mongo:27017/notesdb"
      JWT_SECRET : secret123
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: notes-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  nginx:
    image: nginx:latest
    container_name: notes_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

volumes:
  mongo_data:
